const t={
ru:{
hero_action:"ВРЕМЯ ДЕЙСТВОВАТЬ",hero_sub:"Твой путеводитель к призванию",intro_1:"Ты появился в этом мире не случайно.",intro_2:"Бог создал тебя уникальным. Он вложил в тебя способности, характер, дары, опыт и потенциал.",intro_3:"Этот гайд поможет тебе пройти путь от личных отношений с Богом к пониманию своего призвания, миссии и плода.",eph_text:"«Ибо мы — Его творение, созданы во Христе Иисусе на добрые дела, которые Бог предназначил нам исполнять».",eph_ref:"ЕФЕСЯНАМ 2:10",start_button:"НАЧАТЬ ПУТЬ ↓",path_label:"ТВОЙ ПУТЬ",path_title:"7 ШАГОВ К МИССИИ",task_label:"ЗАДАНИЕ",task_24:"ЗАДАНИЕ: 24 ЧАСА",final_label:"НАЧНИ СЕГОДНЯ",final_title:"Тебе необязательно сегодня знать весь Божий план для своей жизни.",final_line:"Начни с того, что уже понятно.",
s1_title:"ПОЗНАЙ БОГА",s1_lead:"Всё начинается с личных отношений с Богом.",s1_body:"Прежде чем искать своё призвание, начни с Того, Кто тебя создал. Строй отношения с Богом через молитву, Его Слово, поклонение, послушание и общение со Святым Духом.",s1_v1:"«Приблизьтесь к Богу, и приблизится к вам».",s1_r1:"Иакова 4:8",s1_v2:"«Овцы Мои слушаются голоса Моего, и Я знаю их; и они идут за Мною».",s1_r2:"Иоанна 10:27",s1_task:"Выдели время для Бога. Прочитай Иоанна 10:27, помолись и запиши мысли, которые приходят тебе во время молитвы и чтения Писания.",
s2_title:"СТАНЬ ЧАСТЬЮ ПОМЕСТНОЙ ЦЕРКВИ И НАЙДИ ДУХОВНОГО НАСТАВНИКА",s2_lead:"Не проходи этот путь один.",s2_body:"Бог не задумал христианскую жизнь в одиночестве. Будь частью здоровой поместной церкви, служи и имей рядом зрелого духовного наставника, с которым можно молиться, советоваться и обсуждать важные решения.",s2_v1:"«Не будем оставлять собрания своего…»",s2_r1:"Евреям 10:25",s2_v2:"«И вы — тело Христово, а порознь — члены».",s2_r2:"1 Коринфянам 12:27",s2_v3:"«Без совета предприятия расстроятся, а при множестве советников они состоятся».",s2_r3:"Притчи 15:22",s2_task:"Ответь: я действительно являюсь частью поместной церкви? Где я служу? Есть ли у меня духовно зрелый наставник, с которым я могу быть открытым и советоваться?",
s3_title:"ПОЗНАЙ СЕБЯ",s3_lead:"Исследуй то, что Бог уже вложил в тебя.",s3_body:"У каждого человека есть уникальное сочетание талантов, способностей, духовных даров, характера, опыта, интересов и сильных сторон. Не становись копией другого человека — обнаружь то, что Бог доверил тебе.",s3_v1:"«Служите друг другу, каждый тем даром, какой получил…»",s3_r1:"1 Петра 4:10",s3_task:"Запиши минимум 5 своих сильных сторон, талантов или способностей. Затем спроси трёх людей, которые хорошо тебя знают, какие сильные стороны они видят в тебе.",
s4_title:"ИЩИ СВОЁ ПРИЗВАНИЕ",s4_lead:"Спроси Бога, для чего Он дал тебе то, что ты имеешь.",s4_body:"Призвание — это больше, чем профессия. Обращай внимание на людей, проблемы и направления, которые особенно касаются твоего сердца, и проверяй свои выводы через молитву, Писание и совет духовно зрелых людей.",s4_v1:"«Ибо дары и призвание Божие непреложны».",s4_r1:"Римлянам 11:29",s4_task:"Закончи: «Мне особенно хочется помогать…», «Проблема, которую мне особенно хочется решать…», «Для этого я могу использовать…».",
s5_title:"ПРЕВРАТИ ПРИЗВАНИЕ В МИССИЮ",s5_lead:"То, что Бог дал тебе, должно послужить другим.",s5_body:"Твоя миссия может реализовываться через церковь, семью, профессию, бизнес, творчество, образование, социальный проект, медиа, технологии и другие сферы. Форма может быть разной, но в центре остаются Бог и люди.",s5_v1:"«Кто хочет быть большим между вами, тот да будет вам слугою».",s5_r1:"Матфея 20:26",s5_task:"«Я хочу использовать __________, чтобы служить __________ и помогать им __________».",
s6_title:"СДЕЛАЙ ПЕРВЫЙ ШАГ",s6_lead:"Вера должна переходить в действие.",s6_body:"Тебе не обязательно видеть весь путь. Нужно увидеть следующий шаг: начать служить, поговорить с наставником, получить знания, помочь одному человеку, использовать талант или запустить маленький проект.",s6_v1:"«Так и вера, если не имеет дел, мертва сама по себе».",s6_r1:"Иакова 2:17",s6_task:"Запиши свой следующий шаг и в течение следующих 24 часов сделай одно конкретное действие. Не просто подумай об этом — сделай.",
s7_title:"ПРИНОСИ ПЛОД",s7_lead:"Призвание должно приносить плод.",s7_body:"Цель призвания — не только личный успех. Спроси себя: помогает ли моя жизнь людям, приближаются ли они к Богу, меняются ли жизни и использую ли я то, что Бог мне доверил?",s7_v1:"«Тем прославится Отец Мой, если вы принесёте много плода…»",s7_r1:"Иоанна 15:8",s7_v2:"«Без Меня не можете делать ничего».",s7_r2:"Иоанна 15:5"},
ua:{
hero_action:"ЧАС ДІЯТИ",hero_sub:"Твій путівник до покликання",intro_1:"Ти з’явився в цьому світі не випадково.",intro_2:"Бог створив тебе унікальним. Він вклав у тебе здібності, характер, дари, досвід і потенціал.",intro_3:"Цей гайд допоможе пройти шлях від особистих стосунків із Богом до розуміння свого покликання, місії та плоду.",eph_text:"«Бо ми — Його творіння, створені в Христі Ісусі на добрі діла, які Бог наперед приготував, щоб ми в них перебували».",eph_ref:"ЕФЕСЯНАМ 2:10",start_button:"ПОЧАТИ ШЛЯХ ↓",path_label:"ТВІЙ ШЛЯХ",path_title:"7 КРОКІВ ДО МІСІЇ",task_label:"ЗАВДАННЯ",task_24:"ЗАВДАННЯ: 24 ГОДИНИ",final_label:"ПОЧНИ СЬОГОДНІ",final_title:"Тобі не обов’язково сьогодні знати весь Божий план для свого життя.",final_line:"Почни з того, що вже зрозуміло.",
s1_title:"ПІЗНАЙ БОГА",s1_lead:"Усе починається з особистих стосунків із Богом.",s1_body:"Перш ніж шукати своє покликання, почни з Того, Хто тебе створив. Будуй стосунки з Богом через молитву, Його Слово, поклоніння, послух і спілкування зі Святим Духом.",s1_v1:"«Наблизьтеся до Бога, і Він наблизиться до вас».",s1_r1:"Якова 4:8",s1_v2:"«Мої вівці слухають голосу Мого, і Я знаю їх, і вони йдуть за Мною».",s1_r2:"Івана 10:27",s1_task:"Виділи час для Бога. Прочитай Івана 10:27, помолися й запиши думки, які приходять під час молитви та читання Писання.",
s2_title:"СТАНЬ ЧАСТИНОЮ ПОМІСНОЇ ЦЕРКВИ ТА ЗНАЙДИ ДУХОВНОГО НАСТАВНИКА",s2_lead:"Не проходь цей шлях сам.",s2_body:"Бог не задумав християнське життя наодинці. Будь частиною здорової помісної церкви, служи й май поруч зрілого духовного наставника, з яким можна молитися, радитися та обговорювати важливі рішення.",s2_v1:"«Не будемо залишати збору свого…»",s2_r1:"Євреїв 10:25",s2_v2:"«Ви — тіло Христове, а зосібна — члени».",s2_r2:"1 Коринтян 12:27",s2_v3:"«Задум руйнується без ради, а при численності радників здійснюється».",s2_r3:"Приповісті 15:22",s2_task:"Відповідай: чи я справді є частиною помісної церкви? Де я служу? Чи маю духовно зрілого наставника, з яким можу бути відкритим і радитися?",
s3_title:"ПІЗНАЙ СЕБЕ",s3_lead:"Досліди те, що Бог уже вклав у тебе.",s3_body:"У кожної людини є унікальне поєднання талантів, здібностей, духовних дарів, характеру, досвіду, інтересів і сильних сторін. Не ставай копією іншого — відкрий те, що Бог довірив тобі.",s3_v1:"«Служіть один одному, кожен тим даром, якого отримав…»",s3_r1:"1 Петра 4:10",s3_task:"Запиши щонайменше 5 своїх сильних сторін, талантів або здібностей. Потім запитай трьох людей, які добре тебе знають, які сильні сторони вони бачать у тобі.",
s4_title:"ШУКАЙ СВОЄ ПОКЛИКАННЯ",s4_lead:"Запитай Бога, для чого Він дав тобі те, що ти маєш.",s4_body:"Покликання — це більше, ніж професія. Звертай увагу на людей, проблеми й напрямки, які особливо торкаються твого серця, і перевіряй висновки через молитву, Писання та пораду духовно зрілих людей.",s4_v1:"«Бо дари й покликання Божі — невідкличні».",s4_r1:"Римлян 11:29",s4_task:"Закінчи: «Мені особливо хочеться допомагати…», «Проблема, яку мені особливо хочеться вирішувати…», «Для цього я можу використати…».",
s5_title:"ПЕРЕТВОРИ ПОКЛИКАННЯ НА МІСІЮ",s5_lead:"Те, що Бог дав тобі, має послужити іншим.",s5_body:"Твоя місія може реалізовуватися через церкву, сім’ю, професію, бізнес, творчість, освіту, соціальний проєкт, медіа, технології та інші сфери. Форма може бути різною, але в центрі залишаються Бог і люди.",s5_v1:"«Хто хоче бути великим між вами, нехай буде вам слугою».",s5_r1:"Матвія 20:26",s5_task:"«Я хочу використовувати __________, щоб служити __________ і допомагати їм __________».",
s6_title:"ЗРОБИ ПЕРШИЙ КРОК",s6_lead:"Віра має переходити в дію.",s6_body:"Тобі не обов’язково бачити весь шлях. Треба побачити наступний крок: почати служити, поговорити з наставником, здобути знання, допомогти одній людині, використати талант або запустити маленький проєкт.",s6_v1:"«Так само й віра, коли діл не має, мертва сама по собі».",s6_r1:"Якова 2:17",s6_task:"Запиши свій наступний крок і протягом наступних 24 годин зроби одну конкретну дію. Не просто подумай про це — зроби.",
s7_title:"ПРИНОСЬ ПЛІД",s7_lead:"Покликання має приносити плід.",s7_body:"Мета покликання — не лише особистий успіх. Запитай себе: чи допомагає моє життя людям, чи наближаються вони до Бога, чи змінюються життя і чи використовую я те, що Бог мені довірив?",s7_v1:"«Тим прославиться Отець Мій, якщо рясно зародите…»",s7_r1:"Івана 15:8",s7_v2:"«Без Мене нічого чинити не можете».",s7_r2:"Івана 15:5"},
en:{
hero_action:"TIME TO ACT",hero_sub:"Your guide to calling",intro_1:"You are not in this world by accident.",intro_2:"God created you uniquely. He placed abilities, character, gifts, experience and potential within you.",intro_3:"This guide will help you move from a personal relationship with God toward understanding your calling, mission and fruit.",eph_text:"“For we are His workmanship, created in Christ Jesus for good works, which God prepared beforehand that we should walk in them.”",eph_ref:"EPHESIANS 2:10",start_button:"START THE JOURNEY ↓",path_label:"YOUR PATH",path_title:"7 STEPS TO MISSION",task_label:"TASK",task_24:"TASK: 24 HOURS",final_label:"START TODAY",final_title:"You do not have to know God's entire plan for your life today.",final_line:"Start with what is already clear.",
s1_title:"KNOW GOD",s1_lead:"Everything begins with a personal relationship with God.",s1_body:"Before searching for your calling, begin with the One who created you. Build your relationship with God through prayer, His Word, worship, obedience and fellowship with the Holy Spirit.",s1_v1:"“Draw near to God and He will draw near to you.”",s1_r1:"James 4:8",s1_v2:"“My sheep hear My voice, and I know them, and they follow Me.”",s1_r2:"John 10:27",s1_task:"Set aside time for God. Read John 10:27, pray, and write down the thoughts that come to you during prayer and Scripture reading.",
s2_title:"BECOME PART OF A LOCAL CHURCH AND FIND A SPIRITUAL MENTOR",s2_lead:"Do not walk this path alone.",s2_body:"God did not design the Christian life to be lived alone. Become part of a healthy local church, serve, and have a mature spiritual mentor nearby with whom you can pray, seek counsel and discuss important decisions.",s2_v1:"“Not forsaking the assembling of ourselves together…”",s2_r1:"Hebrews 10:25",s2_v2:"“Now you are the body of Christ, and members individually.”",s2_r2:"1 Corinthians 12:27",s2_v3:"“Without counsel, plans go awry, but in the multitude of counselors they are established.”",s2_r3:"Proverbs 15:22",s2_task:"Ask yourself: Am I truly part of a local church? Where do I serve? Do I have a spiritually mature mentor with whom I can be open and seek counsel?",
s3_title:"KNOW YOURSELF",s3_lead:"Explore what God has already placed within you.",s3_body:"Every person has a unique combination of talents, abilities, spiritual gifts, character, experience, interests and strengths. Do not become a copy of someone else—discover what God has entrusted to you.",s3_v1:"“As each one has received a gift, minister it to one another…”",s3_r1:"1 Peter 4:10",s3_task:"Write down at least 5 of your strengths, talents or abilities. Then ask three people who know you well what strengths they see in you.",
s4_title:"SEEK YOUR CALLING",s4_lead:"Ask God why He gave you what you have.",s4_body:"Calling is bigger than a profession. Pay attention to the people, problems and directions that especially move your heart, and test your conclusions through prayer, Scripture and the counsel of spiritually mature people.",s4_v1:"“For the gifts and the calling of God are irrevocable.”",s4_r1:"Romans 11:29",s4_task:"Finish the sentences: “I especially want to help…”, “The problem I especially want to solve is…”, “For this I can use…”.",
s5_title:"TURN CALLING INTO MISSION",s5_lead:"What God gave you should serve others.",s5_body:"Your mission can be expressed through church, family, profession, business, creativity, education, a social project, media, technology and many other areas. The form may differ, but God and people remain at the center.",s5_v1:"“Whoever desires to become great among you, let him be your servant.”",s5_r1:"Matthew 20:26",s5_task:"“I want to use __________ to serve __________ and help them __________.”",
s6_title:"TAKE THE FIRST STEP",s6_lead:"Faith must move into action.",s6_body:"You do not have to see the entire road. You need to see the next step: begin serving, talk with a mentor, gain knowledge, help one person, use your talent or launch a small project.",s6_v1:"“Faith by itself, if it does not have works, is dead.”",s6_r1:"James 2:17",s6_task:"Write down your next step and within the next 24 hours take one concrete action. Do not only think about it—do it.",
s7_title:"BEAR FRUIT",s7_lead:"Calling should bear fruit.",s7_body:"The goal of calling is not only personal success. Ask yourself: Does my life help people, are they drawing closer to God, are lives changing, and am I using what God entrusted to me?",s7_v1:"“By this My Father is glorified, that you bear much fruit…”",s7_r1:"John 15:8",s7_v2:"“Without Me you can do nothing.”",s7_r2:"John 15:5"}};
function setLang(lang){document.documentElement.lang=lang==="ua"?"uk":lang;document.querySelectorAll("[data-i18n]").forEach(el=>{const k=el.dataset.i18n;if(t[lang][k])el.textContent=t[lang][k]});document.querySelectorAll(".lang-switch button").forEach(b=>b.classList.toggle("active",b.dataset.lang===lang));localStorage.setItem("hp-guide-lang",lang)}
document.querySelectorAll(".lang-switch button").forEach(b=>b.addEventListener("click",()=>setLang(b.dataset.lang)));
setLang(localStorage.getItem("hp-guide-lang")||"ru");